title: Travelog
description: Carly & Owen's European Travelog

url: https://oblongcheese.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 3

destination: /var/www/html/
keep_files: [mythweb]

navigation:
 - title: Home
   url: /index.html
 - title: Photo Map
   url: /map.html
 - title: About
   url: /about.html
# - title: Contact
#   url: /contact.html

social:
#   github: brianmaierjr
   twitter: thejimmydimple
#   facebook: brianmaierjr
#   email: owen@owened.net
   instagram: thejimmydimple

#google_analytics: ""
